---
kind: pipeline
type: docker
name: amd64-scp-test

platform:
  arch: amd64
  os: linux

steps:
- name: scp
  image: wryjer/scp
  settings:
    host: 
      from_secret: ssh_host
    port: 22
    username: 
      from_secret: ssh_username
    password: 
      from_secret: ssh_password
    rm: true
    source:
      - hi
      - .drone.yml
    target:
      - hhi
      - drone.yml

trigger:
  event:
    - push
    - tag
